steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'PacMen'
    organization: '417402'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=417402_PacMen
      sonar.projectName=PacMen
- task: Maven@3
  inputs:
    mavenPomFile: 'server/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 1.11
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'

trigger:
- development
- master
- main

pool:
  vmImage: 'ubuntu-latest'